### ISSUE TITLE
Assess Meetup API

### ISSUE THREAD

**Issue by a-kilroy** [mozilla/missy-elephant#17]

**Comment by alanmoo** [comment]
https://docs.google.com/document/d/12ZXvjJJOeqaOeaa15Tr-lqS2SGY3-1aPwmq-qOWYkMU/edit

**Comment by a-kilroy** [comment]
Is the system closed? Seems like we import in but we can't pull info out? So for example, if someone RSVP's we can't get their contact info to send them an email correct?

**Comment by alanmoo** [comment]
We can pull a bunch of info out, but unsurprisingly it doesn't look like we can get a Meetup Member's email.
